name: Scan Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '21 9 * * 3'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan-code:
    name: Scan Code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}

      - name: Set up .NET
        uses: zyactions/dotnet-setup@v1
        with:
          global-json-file: global.json

      - name: Restore .NET dependencies
        uses: zyactions/dotnet-restore@v1

      - name: Build solution
        run: dotnet build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
